### ISSUE TITLE
Feature_importances for multi-class classification

### ISSUE THREAD

**Issue by VinceDem** [artemmavrin/logitboost#2]
Hi!

Great package for implementing Logitboost!

I was wondering if there was any way to get the feature_importances in the case of multi-class classification?

**Comment by artemmavrin** [comment]
Thanks for the feedback!

What do you think would be a good way of quantifying feature importance in the multiclass case? In this case, there is an ensemble of one-vs-rest estimators for each class (so with ensemble size `m` and number of classes `j`, there are `m*j` estimators total). A naive approach would be to average the feature importances over all `m*j` estimators, but I don't know whether this leads to a meaningful aggregate feature importance for the ensemble.
